import dynamic from 'next/dynamic';

export const successLensModuleMap = {
  AlzheimersPollutionLink: dynamic(() => import('../success-lens/AlzheimersPollutionLink')),
  AmazonFresh: dynamic(() => import('../success-lens/AmazonFresh')),
  BewakoofCEOStepsDown: dynamic(() => import('../success-lens/BewakoofCEOStepsDown')),
  Budget2026Overhaul: dynamic(() => import('../success-lens/Budget2026Overhaul')),
  CGPowerOrder: dynamic(() => import('../success-lens/CGPowerOrder')),
  CabinetApprovesFund: dynamic(() => import('../success-lens/CabinetApprovesFund')),
  CarbonCreditStartups: dynamic(() => import('../success-lens/CarbonCreditStartups')),
  D2CBrands: dynamic(() => import('../success-lens/D2CBrands')),
  FintechIPOWavePost: dynamic(() => import('../success-lens/FintechIPOWavePost')),
  GlobalInnovationForumCES: dynamic(() => import('../success-lens/GlobalInnovationForumCES')),
  GoogleAIHub: dynamic(() => import('../success-lens/GoogleAIHub')),
  GoogleGeminiChrome: dynamic(() => import('../success-lens/GoogleGeminiChrome')),
  HandmadeRoots: dynamic(() => import('../success-lens/HandmadeRoots')),
  HypeToHabit: dynamic(() => import('../success-lens/HypeToHabit')),
  IKEATamilNaduOnline: dynamic(() => import('../success-lens/IKEATamilNaduOnline')),
  IndiasDeeptech: dynamic(() => import('../success-lens/IndiasDeeptech')),
  JPMorganEarnings: dynamic(() => import('../success-lens/JPMorganEarnings')),
  LucknowAIHub: dynamic(() => import('../success-lens/LucknowAIHub')),
  NeemansFunding: dynamic(() => import('../success-lens/NeemansFunding')),
  NightSolarTech: dynamic(() => import('../success-lens/NightSolarTech')),
  PhotonicChipNewColors: dynamic(() => import('../success-lens/PhotonicChipNewColors')),
  RBIBorrowingCosts: dynamic(() => import('../success-lens/RBIBorrowingCosts')),
  SamsungPrivacyDisplay: dynamic(() => import('../success-lens/SamsungPrivacyDisplay')),
  SelfHealingConcrete: dynamic(() => import('../success-lens/SelfHealingConcrete')),
  SharkTankHoora: dynamic(() => import('../success-lens/SharkTankHoora')),
  TataMotorsHydrogenBus: dynamic(() => import('../success-lens/TataMotorsHydrogenBus')),
  TorrentPharmaFDA: dynamic(() => import('../success-lens/TorrentPharmaFDA')),
  VigyanShaalaAward: dynamic(() => import('../success-lens/VigyanShaalaAward')),
  WorldTightens: dynamic(() => import('../success-lens/WorldTightens')),
  ZohoArattai: dynamic(() => import('../success-lens/ZohoArattai')),
};
